### PR TITLE
Exception events

### LINKED ISSUE #5: Native Snowplow sdk needs to be upgraded
We are currently using [Android one v1.4.0](https://github.com/HomeXLabs/snowplow-flutter-tracker/blob/main/android/build.gradle) and [iOS one v1.3.0](https://github.com/HomeXLabs/snowplow-flutter-tracker/blob/main/ios/snowplow_flutter_tracker.podspec).

But these are the latest version: [Android latest v1.7.1 ](https://github.com/snowplow/snowplow-android-tracker/releases) and [iOS latest v1.6.2](https://github.com/snowplow/snowplow-objc-tracker/releases).

### LINKED ISSUE #11: Add setExceptionEvents
SPTracker allows to [track exception events](https://github.com/snowplow/snowplow-objc-tracker/blob/5c3f00d9f9168a7089e5075f45ddfc27cb4c1582/Snowplow/SPTracker.m#L317) (like crashes). Currently, we don't allow adding setting that flag on TrackerBuilder. 

Let's add support for exception events. :)

### PR DESCRIPTION
**Pull request by ohitsdaniel**
Resolves #5. Resolves #11.

Snowplow added exception event tracking to their SDKs. This PR adds the setExceptionEvents to TrackerBuilder and sets the according options on the native counterparts.

Also updates the Android Native Snowplow SDK to the latest version.

### CODE REVIEW

**Review by MisterJimson — CHANGES_REQUESTED** [review]
Thanks for the PRs! When testing, it fails to compile on Android. Line 15 on SnowplowFlutterTracker.kt.

Seems like `waitForEventStore` doesn't exsit anymore.

**Comment by ohitsdaniel** [comment]
Oops, sorry, missed that one. I'll look into it tomorrow :)

**Comment by MisterJimson** [comment]
@ohitsdaniel are you still interested in fixing the above issue? If not no worries I can look at it at some point.

**Comment by ohitsdaniel** [comment]
@MisterJimson yes! I just have the week off and haven't gotten back to it :)

**Comment by ohitsdaniel** [comment]
https://github.com/snowplow-incubator/snowplow-react-native-tracker/issues/91#issuecomment-686393412

I looked up what happened to `waitForEventStore` and apparently it was removed because the latest version no longer needs for the DB to initialised. So, we can just remove the call.

**Review by MisterJimson — APPROVED** [review]

**Pull request merged**
