### PR TITLE
Remove the builder pattern

### PR DESCRIPTION
**Pull request by MisterJimson**

### CODE REVIEW

**Comment by ohitsdaniel** [comment]
What do you think about marking all the event types as `@immutable` (they're basically value types, right?) and adding Equatable (https://pub.dev/packages/equatable) conformance to all of them? In that way, we can easily test that the correct event was sent through tracker.track().

I was basically writing a similar abstraction on top of this library to remove the oldschool iOS builder pattern. As part of that, we could also tackle null-safety as optional fields could be marked as optional in this overhaul.

**Comment by MisterJimson** [comment]
They are immutable right now. We could add the annotation, but it just lints to make sure you don't accidentally make a field non final.

I am open to including equatable, I have used it before. My only concern is adding a new transitive dependancy for library users.

**Comment by MisterJimson** [comment]
I've decided to go without equatable for now to keep the dependancy chain small. I've additionally removed the built value packages for the same reason. The library no longer needs code generation at all.

Null safety is next up.

**Comment by ohitsdaniel** [comment]
Nice! Feel free to ping me when you need help/want me to work on something. I have some capacity this week and dedicated some time to contributing to this library. :)

**Pull request merged**
